const DATABASE_NAME = '@gameplay';

const COLLECTION_USER = `${DATABASE_NAME}:user`
const COLLECTION_APPOINTMENT = `${DATABASE_NAME}:appointment`

export {
    COLLECTION_APPOINTMENT,
    COLLECTION_USER
}